/**
 * synactaclientjs
 * WebApi
 *
 * OpenAPI spec version: v1
 * Contact: bhofmann@agile-is.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Right'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Right'));
  } else {
    // Browser globals (root is window)
    if (!root.Synactaclientjs) {
      root.Synactaclientjs = {};
    }
    root.Synactaclientjs.Role = factory(root.Synactaclientjs.ApiClient, root.Synactaclientjs.Right);
  }
}(this, function(ApiClient, Right) {
  'use strict';




  /**
   * The Role model module.
   * @module model/Role
   * @version v1
   */

  /**
   * Constructs a new <code>Role</code>.
   * @alias module:model/Role
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>Role</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Role} obj Optional instance to populate.
   * @return {module:model/Role} The populated <code>Role</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('rights')) {
        obj['rights'] = ApiClient.convertToType(data['rights'], [Right]);
      }
      if (data.hasOwnProperty('@odata.context')) {
        obj['@odata.context'] = ApiClient.convertToType(data['@odata.context'], 'String');
      }
      if (data.hasOwnProperty('@odata.readLink')) {
        obj['@odata.readLink'] = ApiClient.convertToType(data['@odata.readLink'], 'String');
      }
      if (data.hasOwnProperty('FullODataLink@odata.navigationLink')) {
        obj['FullODataLink@odata.navigationLink'] = ApiClient.convertToType(data['FullODataLink@odata.navigationLink'], 'String');
      }
      if (data.hasOwnProperty('StandardODataLink@odata.navigationLink')) {
        obj['StandardODataLink@odata.navigationLink'] = ApiClient.convertToType(data['StandardODataLink@odata.navigationLink'], 'String');
      }
      if (data.hasOwnProperty('NoneODataLink@odata.navigationLink')) {
        obj['NoneODataLink@odata.navigationLink'] = ApiClient.convertToType(data['NoneODataLink@odata.navigationLink'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Array.<module:model/Right>} rights
   */
  exports.prototype['rights'] = undefined;
  /**
   * @member {String} @odata.context
   */
  exports.prototype['@odata.context'] = undefined;
  /**
   * @member {String} @odata.readLink
   */
  exports.prototype['@odata.readLink'] = undefined;
  /**
   * @member {String} FullODataLink@odata.navigationLink
   */
  exports.prototype['FullODataLink@odata.navigationLink'] = undefined;
  /**
   * @member {String} StandardODataLink@odata.navigationLink
   */
  exports.prototype['StandardODataLink@odata.navigationLink'] = undefined;
  /**
   * @member {String} NoneODataLink@odata.navigationLink
   */
  exports.prototype['NoneODataLink@odata.navigationLink'] = undefined;



  return exports;
}));


