/**
 * synactaclientjs
 * WebApi
 *
 * OpenAPI spec version: v1
 * Contact: bhofmann@agile-is.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Synactaclientjs);
  }
}(this, function(expect, Synactaclientjs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Synactaclientjs.AuthorizationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthorizationApi', function() {
    describe('apiAuthorizationPrincipalsByIdGet', function() {
      it('should call apiAuthorizationPrincipalsByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiAuthorizationPrincipalsByIdGet
        //instance.apiAuthorizationPrincipalsByIdGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiAuthorizationPrincipalsGet', function() {
      it('should call apiAuthorizationPrincipalsGet successfully', function(done) {
        //uncomment below and update the code to test apiAuthorizationPrincipalsGet
        //instance.apiAuthorizationPrincipalsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiAuthorizationRightsGet', function() {
      it('should call apiAuthorizationRightsGet successfully', function(done) {
        //uncomment below and update the code to test apiAuthorizationRightsGet
        //instance.apiAuthorizationRightsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiAuthorizationRolesAddGet', function() {
      it('should call apiAuthorizationRolesAddGet successfully', function(done) {
        //uncomment below and update the code to test apiAuthorizationRolesAddGet
        //instance.apiAuthorizationRolesAddGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiAuthorizationRolesAddPut', function() {
      it('should call apiAuthorizationRolesAddPut successfully', function(done) {
        //uncomment below and update the code to test apiAuthorizationRolesAddPut
        //instance.apiAuthorizationRolesAddPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiAuthorizationRolesByIdDelete', function() {
      it('should call apiAuthorizationRolesByIdDelete successfully', function(done) {
        //uncomment below and update the code to test apiAuthorizationRolesByIdDelete
        //instance.apiAuthorizationRolesByIdDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiAuthorizationRolesByIdGet', function() {
      it('should call apiAuthorizationRolesByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiAuthorizationRolesByIdGet
        //instance.apiAuthorizationRolesByIdGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiAuthorizationRolesByIdPost', function() {
      it('should call apiAuthorizationRolesByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiAuthorizationRolesByIdPost
        //instance.apiAuthorizationRolesByIdPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiAuthorizationRolesGet', function() {
      it('should call apiAuthorizationRolesGet successfully', function(done) {
        //uncomment below and update the code to test apiAuthorizationRolesGet
        //instance.apiAuthorizationRolesGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
