/**
 * synactaclientjs
 * WebApi
 *
 * OpenAPI spec version: v1
 * Contact: bhofmann@agile-is.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Synactaclientjs);
  }
}(this, function(expect, Synactaclientjs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Synactaclientjs.BaseApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BaseApi', function() {
    describe('apiBaseByTypeByIdAddByNewContainerTypeGet', function() {
      it('should call apiBaseByTypeByIdAddByNewContainerTypeGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdAddByNewContainerTypeGet
        //instance.apiBaseByTypeByIdAddByNewContainerTypeGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdAddPut', function() {
      it('should call apiBaseByTypeByIdAddPut successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdAddPut
        //instance.apiBaseByTypeByIdAddPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdCheckinPut', function() {
      it('should call apiBaseByTypeByIdCheckinPut successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdCheckinPut
        //instance.apiBaseByTypeByIdCheckinPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdCheckoutPut', function() {
      it('should call apiBaseByTypeByIdCheckoutPut successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdCheckoutPut
        //instance.apiBaseByTypeByIdCheckoutPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdChildrenGet', function() {
      it('should call apiBaseByTypeByIdChildrenGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdChildrenGet
        //instance.apiBaseByTypeByIdChildrenGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdChildrenTypesGet', function() {
      it('should call apiBaseByTypeByIdChildrenTypesGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdChildrenTypesGet
        //instance.apiBaseByTypeByIdChildrenTypesGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdDelete', function() {
      it('should call apiBaseByTypeByIdDelete successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdDelete
        //instance.apiBaseByTypeByIdDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdDocumentsGet', function() {
      it('should call apiBaseByTypeByIdDocumentsGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdDocumentsGet
        //instance.apiBaseByTypeByIdDocumentsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdDocumentsTypesGet', function() {
      it('should call apiBaseByTypeByIdDocumentsTypesGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdDocumentsTypesGet
        //instance.apiBaseByTypeByIdDocumentsTypesGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdGet', function() {
      it('should call apiBaseByTypeByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdGet
        //instance.apiBaseByTypeByIdGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdGetFileGet', function() {
      it('should call apiBaseByTypeByIdGetFileGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdGetFileGet
        //instance.apiBaseByTypeByIdGetFileGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdLookupListByLookupListNameGet', function() {
      it('should call apiBaseByTypeByIdLookupListByLookupListNameGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdLookupListByLookupListNameGet
        //instance.apiBaseByTypeByIdLookupListByLookupListNameGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdMovePost', function() {
      it('should call apiBaseByTypeByIdMovePost successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdMovePost
        //instance.apiBaseByTypeByIdMovePost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdPost', function() {
      it('should call apiBaseByTypeByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdPost
        //instance.apiBaseByTypeByIdPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdUploadFilePost', function() {
      it('should call apiBaseByTypeByIdUploadFilePost successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdUploadFilePost
        //instance.apiBaseByTypeByIdUploadFilePost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdVersionsByVersionIdGet', function() {
      it('should call apiBaseByTypeByIdVersionsByVersionIdGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdVersionsByVersionIdGet
        //instance.apiBaseByTypeByIdVersionsByVersionIdGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdVersionsByVersionIdGetFileGet', function() {
      it('should call apiBaseByTypeByIdVersionsByVersionIdGetFileGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdVersionsByVersionIdGetFileGet
        //instance.apiBaseByTypeByIdVersionsByVersionIdGetFileGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdVersionsByVersionIdRestorePost', function() {
      it('should call apiBaseByTypeByIdVersionsByVersionIdRestorePost successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdVersionsByVersionIdRestorePost
        //instance.apiBaseByTypeByIdVersionsByVersionIdRestorePost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeByIdVersionsGet', function() {
      it('should call apiBaseByTypeByIdVersionsGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeByIdVersionsGet
        //instance.apiBaseByTypeByIdVersionsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseByTypeGet', function() {
      it('should call apiBaseByTypeGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseByTypeGet
        //instance.apiBaseByTypeGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseRootGet', function() {
      it('should call apiBaseRootGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseRootGet
        //instance.apiBaseRootGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiBaseTypesGet', function() {
      it('should call apiBaseTypesGet successfully', function(done) {
        //uncomment below and update the code to test apiBaseTypesGet
        //instance.apiBaseTypesGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
