/**
 * synactaclientjs
 * WebApi
 *
 * OpenAPI spec version: v1
 * Contact: bhofmann@agile-is.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Synactaclientjs);
  }
}(this, function(expect, Synactaclientjs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Synactaclientjs.OrganisationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrganisationApi', function() {
    describe('apiOrgByIdAddGet', function() {
      it('should call apiOrgByIdAddGet successfully', function(done) {
        //uncomment below and update the code to test apiOrgByIdAddGet
        //instance.apiOrgByIdAddGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgByIdAddPut', function() {
      it('should call apiOrgByIdAddPut successfully', function(done) {
        //uncomment below and update the code to test apiOrgByIdAddPut
        //instance.apiOrgByIdAddPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgByIdByTypeGet', function() {
      it('should call apiOrgByIdByTypeGet successfully', function(done) {
        //uncomment below and update the code to test apiOrgByIdByTypeGet
        //instance.apiOrgByIdByTypeGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgByIdChildrenGet', function() {
      it('should call apiOrgByIdChildrenGet successfully', function(done) {
        //uncomment below and update the code to test apiOrgByIdChildrenGet
        //instance.apiOrgByIdChildrenGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgByIdDelete', function() {
      it('should call apiOrgByIdDelete successfully', function(done) {
        //uncomment below and update the code to test apiOrgByIdDelete
        //instance.apiOrgByIdDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgByIdGet', function() {
      it('should call apiOrgByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrgByIdGet
        //instance.apiOrgByIdGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgByIdMovePost', function() {
      it('should call apiOrgByIdMovePost successfully', function(done) {
        //uncomment below and update the code to test apiOrgByIdMovePost
        //instance.apiOrgByIdMovePost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgByIdPost', function() {
      it('should call apiOrgByIdPost successfully', function(done) {
        //uncomment below and update the code to test apiOrgByIdPost
        //instance.apiOrgByIdPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgByIdRecycleBinByRecycleBinIdGet', function() {
      it('should call apiOrgByIdRecycleBinByRecycleBinIdGet successfully', function(done) {
        //uncomment below and update the code to test apiOrgByIdRecycleBinByRecycleBinIdGet
        //instance.apiOrgByIdRecycleBinByRecycleBinIdGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgByIdRecycleBinByRecycleBinIdRestorePost', function() {
      it('should call apiOrgByIdRecycleBinByRecycleBinIdRestorePost successfully', function(done) {
        //uncomment below and update the code to test apiOrgByIdRecycleBinByRecycleBinIdRestorePost
        //instance.apiOrgByIdRecycleBinByRecycleBinIdRestorePost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgByIdRecycleBinGet', function() {
      it('should call apiOrgByIdRecycleBinGet successfully', function(done) {
        //uncomment below and update the code to test apiOrgByIdRecycleBinGet
        //instance.apiOrgByIdRecycleBinGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgGet', function() {
      it('should call apiOrgGet successfully', function(done) {
        //uncomment below and update the code to test apiOrgGet
        //instance.apiOrgGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiOrgOrgTreeGet', function() {
      it('should call apiOrgOrgTreeGet successfully', function(done) {
        //uncomment below and update the code to test apiOrgOrgTreeGet
        //instance.apiOrgOrgTreeGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
